# Constants
DOC_HT_SIZE = 50000
GLOB_HT_SIZE = 350000
STOP_HT_SIZE = 3000
TERM_LENGTH = 16
NUMDOCS_LENGTH = 4
START_LENGTH = 12
DOCID_LENGTH = 3
WEIGHT_LENGTH = 9
MAPNAME_LENGTH = 13
DICT_RECORD_SIZE = TERM_LENGTH + NUMDOCS_LENGTH + START_LENGTH + 3
POST_RECORD_SIZE = DOCID_LENGTH + WEIGHT_LENGTH + 2